name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Test CLI functionality
      run: |
        # Test basic functionality
        cargo run -- --help
        cargo run -- --init-config
        
        # Test different output formats
        cargo run -- --format txt src/main.rs > test_output.txt
        cargo run -- --format json src/main.rs > test_output.json
        cargo run -- --format md src/main.rs > test_output.md
        cargo run -- --format xml src/main.rs > test_output.xml
        
        # Verify outputs are not empty
        [ -s test_output.txt ] && echo "TXT output OK"
        [ -s test_output.json ] && echo "JSON output OK" 
        [ -s test_output.md ] && echo "Markdown output OK"
        [ -s test_output.xml ] && echo "XML output OK"
      shell: bash

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust 1.70
      uses: dtolnay/rust-toolchain@1.70

    - name: Check MSRV
      run: cargo check